# Kubernetes ServiceAccount linked to GCP Service Account via Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maplejuris-workload
  annotations:
    iam.gke.io/gcp-service-account: maplejuris-workload-sa@maplejuris-ai.iam.gserviceaccount.com

