apiVersion: v1
kind: Service
metadata:
  name: maplejuris-api
  labels:
    app: maplejuris-api
spec:
  type: NodePort
  selector:
    app: maplejuris-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

